---
- name: Insalling Nginx
  apt:
    name: "{{ pkg }}"
    update_cache: yes
    state: present
  notify:
      - start webserver

- name: copying index.html
  copy:
    src: index.html
    dest: /var/www/html/
    backup: yes
  notify:
     - start webserver
