---
- hosts: localhost
  vars:
    do_token: "XXXXXXXX" 
  tasks:
    - name: creating a VM
      digital_ocean:
        api_token: "{{ do_token }}"
        command: droplet
        name: <XXXXX>
        size_id: 1gb
        region_id: blr1
        image_id: 32481995
        ssh_key_ids: <XXXXX>
        wait_timeout: 500 
