---
- hosts: client1
  tasks:
    - name: creating multiple users
      user:
        name: "{{ item }}"
        state: present
        groups: "wheel"
      with_items:
        - user1
        - user2
        - user3
