---
- hosts: client1
  tasks:
    - name: creating multiple users
      user:
        name: "{{ item }}"
        state: present
        groups: "sudo"
      with_items:
        - king
        - queen
        - jack
