---
- hosts: client1
  vars_prompt:
    - name: password
      prompt: "enter the password"
      encrypt: "sha512_crypt"
      private: yes
      confirm: yes
  tasks:
      - name: user creation
        user:
           name: "{{ item }}"
           password: "{{ password }}"
           createhome: yes
           state: present
        with_items:
           - karthik
           - anand 
