---
- hosts: client1
  tasks:
     - name: ubuntu
       apt:
         name: mariadb-server
         state: latest
         update_cache: yes          
       when:
         - ansible_distribution == "Ubuntu" 
         - ansible_distribution_major_version == "14"

     - name: centos
       yum:
         name: mariadb-server
         state: latest
         update_cache: yes
       when:
         - ansible_distribution == "CentOS"
