---
- name: installing apache2
  apt:
     name: "{{ pkgname }}"
     update_cache: yes
     state: present
  notify:
     - webserver-start

- name: creating webroot
  file:
    path: /var/www/html/{{ webroot }}
    state: directory
    mode: 0775

- name: creating log dir
  file:
    path: /var/log/apache2/{{ webroot }}
    state: directory
    mode: 0775

- name: rendering template
  template:
     src: vwebsite.j2
     dest: /etc/apache2/sites-enabled/{{ domain_name }}.conf

- name: copy the index.html file
  copy:
    src: "{{ webroot }}"
    dest: /var/www/html/{{ webroot }}/index.html
  notify:
      - webserver-reload

...
